title: Karla Fordham
author: Karla Fordham
email: 
description: > # this means to ignore newlines until "twitter_username:"
  Designer of things.
  
header_pages:
 - about.md
 - words.md
 
 minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
